<style type="text/css">
body, td {font-size: 12px}
code.r{font-size: 9px}
pre {font-size: 12px}
</style>
***
#### Appendix S2 - Using R to investigate the impact of environmental factors on lineage dispersal velocity
##### Simon Dellicour (28-06-2018)
***
The present appendix describes how we used the package "seraphim" (Dellicour *et al*. 2016a, Dellicour *et al*. 2016b) to exploit phylogenetically-informed movement data for studying the association between particular environmental factors and the dispersal velocity of the H5N1 virus lineages in the Mekong region.

***
The preliminary step is to download the R package "seraphim" (evolve.zoo.ox.ac.uk/Evolve/Software.html) and place the "seraphim\_1.0.beta.tar.gz" file in a R workspace directory. The package could then be installed from this archive file using the following R command:
```
install.packages("seraphim_1.0.beta.tar.gz", repos=NULL, type="source")
```
Note that this package requires the preliminary installation of the following R packages: "ape", "doMC", "fields", "gdistance", "gstat", "ks", "MASS", "phytools", "raster", "RColorBrewer", "vegan" and "rgdal" (which requires the preliminary installation of "GDAL", a C++ library for reading and writing raster geospatial data formats; www.gdal.org). Once the "seraphim" package is installed, it can be loaded with the following command:
```
library(seraphim)
```

**Step 1: extracting spatio-temporal information in trees**
The next step consists in extracting the spatio-temporal information embedded in posterior trees obtained by continuous phylogeographic inference (Lemey *et al*. 2010). As detailed in the main text, a distinct continuous phylogeographic analysis was performed for each H5N1 clade considered in this study. In practice, we use the “treeExtractions” function of the package “seraphim” to extract the spatio-temporal information from 100 trees sampled at regular intervals from each posterior distribution (after burn-in had been removed).

The "treeExtractions" function first requires the definition of the following parameters: "localTreesDirectory" (name of the directory to create and where spatio-temporal information contained in each tree will be saved), "allTrees" (name of the ".trees" file), "burnIn" (number of trees to discard as burn-in, i.e. a number defining a series of first trees in which no tree will be sampled), "randomSampling" (boolean variable specifying if the trees have to be randomly sampled or sampled at the largest possible regular interval), "nberOfTreesToSample" (number of trees to sample), "mostRecentSamplingDatum" (most recent sampling datum in a decimal format) and "coordinateAttributeName" (attribute name used to indicate the geographic coordinates within the tree file). As they are five distinct continuous phylogeographic outputs corresponding the five ditsinct H5N1 clades analysed in this study, we used a loop to perform five distinct extractions:
```
clades = list(); burnIns = list(); mostRecentSamplingDates = list()
clades[[1]] = "H5N1_Mekong_clade1"; burnIns[[1]] = 1501; mostRecentSamplingDates[[1]] = 2010
clades[[2]] = "H5N1_Mekong_clade11"; burnIns[[1]] = 100; mostRecentSamplingDates[[2]] = 2008
clades[[3]] = "H5N1_Mekong_clade112"; burnIns[[1]] = 100; mostRecentSamplingDates[[3]] = 2012
clades[[4]] = "H5N1_Mekong_clade234"; burnIns[[1]] = 100; mostRecentSamplingDates[[4]] = 2008
clades[[5]] = "H5N1_Mekong_clade2343"; burnIns[[1]] = 100; mostRecentSamplingDates[[5]] = 2009
randomSampling = FALSE
nberOfTreesToSample = 100
coordinateAttributeName = "location"
for (i in 1:length(clades)) {
	localTreesDirectory = paste0("Tree_extractions/",clades[[i]])
	allTrees = scan(file=paste0("BEAST_analyses/",clades[[i]],".trees"), what="", sep="\n", quiet=TRUE)
	burnIn = burnIns[[i]]; mostRecentSamplingDatum = mostRecentSamplingDates[[i]]
	treeExtractions(localTreesDirectory, allTrees, burnIn, randomSampling, nberOfTreesToSample,
					mostRecentSamplingDatum, coordinateAttributeName)
}
```
Specifically, each phylogenetic branch was considered a vector defined by its start and end location (latitude and longitude), and its start and end dates (in decimal units). Each phylogeny branch therefore represents a conditionally independent viral lineage dispersal event (Pybus *et al*. 2012). For the analysis of environmental factors, we gathered all movement vectors extracted from the different H5N1 clades:
```
dir.create(file.path("Tree_extractions/H5N1_Mekong_allClades"), showWarnings=F)
for (i in 1:nberOfTreesToSample) {
	tab = c()
	for (j in 1:length(clades)) {
		if (j == 1) {
			tab = read.csv(paste("Tree_extractions/",clades[j],"/TreeExtractions_",i,".csv",sep=""), header=T)
		}	else		{
			csv = read.csv(paste("Tree_extractions/",clades[j],"/TreeExtractions_",i,".csv",sep=""), header=T)
			maxNodeID = max(tab[,c("node1","node2")])
			csv[,c("node1","node2")] = csv[,c("node1","node2")] + maxNodeID
			tab = rbind(tab, csv)
		}
	}
	write.csv(tab, paste("Tree_extractions/H5N1_Mekong_allClades/TreeExtractions_",i,".csv",sep=""))
}
```

**Step 2: estimating the correlation between branch durations and environmental distances**
All the vectors obtained in step 1 were assigned an environmental distance, i.e. a spatial distance that was weighted according to the values of an environmental raster at each location. We use two distinct path models to compute the environmental distance allocated to each phylogeny branch for a given environmental factor: (i) the least-cost path model, which uses a least-cost algorithm to determine the route taken between the start and end points (Dijkstra 1959), and (ii) the Circuitscape path model, which uses circuit theory to accommodate uncertainty in the route taken (McRae 2006, McRae *et al*. 2008). For these path models, each environmental raster is considered once as a potential resistance factor (i.e. impedes movement) and once as a potential conductance factor (i.e. as a variable that facilitates movement). In the context of the present study, we investigate the impact of the following environmental factors (Fig. S3): elevation, land cover variables (“croplands”, “forests”, “savannas”), inaccessibility (quantified as the time it takes to travel to the nearest major city of >50,000 inhabitants), as well as human, poultry and duck population densities. Further, several distinct rasters are generated by transforming original raster cell values with the following formula: $v_t = 1 + k*(v_o/v_{max})$, where $v_t$ and vo are the transformed and original raster cell values, and $v_{max}$ the maximum raster cell value recorded in the raster. The rescaling parameter $k$ here allows the definition and testing of different strengths of raster cell conductance or resistance, relative to the conductance/resistance of a cell with a minimum value set to “1”. For each environmental factor, we test three different values for $k$ (i.e. 10, 100 and 1000). The list of all the rasters to test is created as follows:
```
rasters = c("Cover_land_croplands_VI_0.08","Cover_land_forests_VI_0.08","Cover_land_savannas_VI_0.08",
			"Pop_density_VI_0.08","Chickens_pop_VI_0.08","Ducks_pop_VI_0.08","Accessibility_VI_0.08","Elevation_VI_0.08")
envVariables = list(); resistances = list(); avgResistances = list(); c = 0
for (k in c(10,100,1000)) {
	for (i in 1:length(rasters)) {
		c = c+1
		rast = raster(paste("Environmental_files/H5N1_rasters/",rasters[i],".asc",sep=""))
		rast[rast[]<0] = 0
		if ((rasters[i] == "Pop_density")|(rasters[i] == "Chickens_pop")|(rasters[i] == "Ducks_pop"))
			{
				rast[] = rast[]+1; rast[] = log10(rast[])
			}
		M = max(rast[], na.rm=T); rast[] = (rast[]*(k/M))+1
		names(rast) = paste(rasters[i],"_k",k,sep="")
		envVariables[[c]] = rast; names(envVariables[[c]]) = paste(rasters[i],"_k",k,sep="")
		resistances[[c]] = TRUE; avgResistances[[c]] = TRUE
	}
	for (i in 1:length(rasters)) {
		c = c+1
		rast = raster(paste("Environmental_files/H5N1_rasters/",rasters[i],".asc",sep=""))
		rast[rast[]<0] = 0
		if ((rasters[i] == "Pop_density")|(rasters[i] == "Chickens_pop")|(rasters[i] == "Ducks_pop")) {
			rast[] = rast[]+1; rast[] = log10(rast[])
		}
		M = max(rast[], na.rm=T); rast[] = (rast[]*(k/M))+1
		names(rast) = paste(rasters[i],"_k",k,sep="")
		envVariables[[c]] = rast; names(envVariables[[c]]) = paste(rasters[i],"_k",k,sep="")
		resistances[[c]] = FALSE; avgResistances[[c]] = FALSE
	}
}
```
Note that the "envVariables" object has to be a list of raster files. Similarly, the "resistances" and "avgResistances" objects have to be created as two vectors of boolean variables specifying if each raster has to be treated as a resistance ("TRUE") or a conductance ("FALSE") variable and if the raster cells have to be connected by average resistance ("TRUE") or average conductance ("FALSE"), respectively. The "avgResistances" list of boolean variables is only important when using the Circuitscape path model. As stated above, we test each raster once as resistance and once as a conductance factor. Note that the different population density rasters are log-transformed in order to avoid providing an excessive weight to a few areas associated with high values. The remaining parameters of the "spreadFactors" function can then be specified as follows:

```
localTreesDirectory = "Tree_extractions/H5N1_Mekong_allClades"
nberOfExtractionFiles = 100
nberOfRandomisations = 1
randomProcedure = 3
fourCells = TRUE
variogramModels = list()
showingPlots = FALSE
nberOfCores = 10
OS = "Unix"
```
The "localTreesDirectory" variable specifies the directory in which the tree extractions files have been saved, and the "nberOfExtractionFiles" parameter specifies the number of tree extraction files to use. As for the "nberOfRandomisations" parameter, it specifies the number of randomisation steps to perform and is here set to "1", which is enough for obtaining Bayes factor like supports (Dellicour *et al*. 2017). The "randomProcedure" parameter determines the randomisation procedure to use, and we here choose the 3rd procedure implemented in "seraphim" (i.e. a randomisation of tree branches positions, see below). "fourCells" is a boolean variable specifying if a given raster cell is connected to its four (TRUE) or eight (FALSE) neighbours (only important for the Circuitscape path model). The "variogramModels" list is not used here but have to be created anyway, i.e. by creating an empty list (the variogram model for each tested raster is necessary when using the raster simulations procedure and can be estimated using the "variogramModel" function also available in the package "seraphim"; see the package manual for further details). If the boolean parameter "showingPlots" is set to "TRUE", the function will generate several plots displaying the position of actual/randomised trees superimposed on the raster being analysed (but the function will then run much slower). Finally, we also have to specify the number of cores or CPUs ("nberOfCores") to use and the operating system on which the function will run. The information about the nature of the operating system is only useful when the function has to call the "Circuitscape" Python package (McRae 2006; see also the package manual for further details). When the "nberOfCores" is higher than one, it is advised to launch the R script from a terminal rather from a R console or R Studio. The function was then launched using the following commands:
```
pathModel = 2; outputName = paste("H5N1_allClades_least-cost",sep="")
spreadFactors(localTreesDirectory, nberOfExtractionFiles, envVariables, pathModel, resistances, avgResistances, fourCells,
			  nberOfRandomisations, randomProcedure, outputName, variogramModels, showingPlots, nberOfCores, OS)
pathModel = 3; outputName = paste("H5N1_allClades_circuitscape",sep="")
spreadFactors(localTreesDirectory, nberOfExtractionFiles, envVariables, pathModel, resistances, avgResistances, fourCells,
			  nberOfRandomisations, randomProcedure, outputName, variogramModels, showingPlots, nberOfCores, OS)
```
As detailed and mentioned above, we performed all the analyses by considering two distinct path models: the least-cost path model ("pathModel = 2") and the Circuitscape path model ("pathModel = 3"). N.B.: "pathModel = 1" corresponds to an unrealistic straight-line path model and is not investigated here.

The "spreadFactors" function performs two distinct analytical steps. Firstly, the correlation between branch durations and environmental distances is estimated for each sampled tree. Specifically, it estimates the statistic $Q = R^2_{env} - R^2_{null}$, where $R^2_{env}$ is the coefficient of determination obtained when branch durations are regressed against environmental distances computed on the environmental raster, and $R^2_{null}$ is the coefficient of determination obtained when branch durations are regressed against environmental distances computed on the “null” raster, i.e. the environmental raster with a value of "1" assigned to all the cells (except cells with no original data). The $Q$ statistic therefore represents how much variation in lineage movement is explained when spatial heterogeneity in the environmental variable is taken into account, above and beyond that explained by distance alone (Dellicour *et al*. 2016a). Therefore, when $Q > 0$, distances weighted according to a heterogeneous environmental raster are correlated more strongly with branch durations than distances computed on a “null” raster (which represents geographical distance alone). Since one $Q$ value was calculated per sampled tree, we then obtained 100 $Q$ values for each combination of environmental factor, $k$ parameter value and selected path model. A variable can only be considered as potentially explanatory if both its distribution of regression coefficients and associated distribution of $Q$ values are positive (Jacquot *et al*. 2017). Indeed, negative regression coefficients indicate that branch durations are negatively correlated with environmental distances and negative $Q$ values indicate that considering environmental distances computed on the environmental raster rather than on the null raster does not improve the linear regression fit. The statistical significance of a $Q$ distribution was thus only considered when at least 90% of the estimated $Q$ values were positive (see below).

Secondly, The statistical significance of the $Q$ distributions is tested using a null model. To generate an appropriate null distribution for $Q$, we use a specific randomisation procedure (Dellicour *et al*. 2016a): phylogenetic node positions are randomised within the study area, under the constraint that branch lengths, tree topology and root position are unchanged. Each sampled posterior tree is randomised once to generate null distributions of $Q$ values that can be directly compared with the posterior distributions of estimated $Q$ values. Each estimated $Q$ value ($Q_{estimated}$) is then compared to its corresponding randomised value ($Q_{randomised}$) to compute a Bayes factor (BF). The BF support for a particular environmental factor was approximated by the posterior odds that $Q_{estimated} > Q_{randomised}$ divided by the equivalent prior odds (the prior probability for $Q_{estimated} > Q_{randomised}$ is considered to be 0.5):
$$BF = \frac{p_e/(1-p_e)}{0.5/(1-0.5)}$$
where $p_e$ is the posterior probability that $Q_{estimated} > Q_{randomised}$, i.e. the frequency at which $Q_{estimated} > Q_{randomised}$ in the sampled posterior distribution. The prior odds is "1" because we have an equal prior expectation for $Q_{estimated}$ and $Q_{randomised}$. The formal estimate of posterior predictive odds is analogous to computing Bayes Factors in case two alternative hypotheses exist, such for the inclusion of rate parameters or predictors in BSSVS procedures (Bayesian stochastic search variable selection; see equation n°6 in Lemey *et al*. 2009). As described in the scale of interpretation of BF’s defined by Kass & Raftery (1995), BF values higher than 3 and 20 can be respectively considered as “positive” and “strong” evidences of the statistical significance of $Q_{estimated}$.

In practice, the function generates two text files: one containing the $Q$ values and one reporting the BF supports. Positive $Q$ distributions, i.e. $Q$ distributions with at least 90% of positive values, as well as their associated Bayes factor are displayed and reported in Figure S4. As we can see in this figure, none of the positive $Q$ distributions is associated with a Bayes factor higher than 20 (and even higher than 5.5), indicating no "strong" evidence for a significant link between the tested environmental factors and H5N1 lineages dispersal velocity.

***
